<?php

namespace Exdda\Controllers\Meta\Types; 

class Page {

    public function __construct() { 
        add_action('acf/init', [$this, 'create_post_meta'], 1); 
    }  

    public static function create_post_meta() {  
         
        if ( function_exists('acf_add_local_field_group') ):  
            acf_add_local_field_group(array(
                'key' => 'group_5641cf6bae146',
                'title' => 'Indhold',
                'fields' => array(
                    array(
                        'key' => 'field_5641cf70ee44c',
                        'label' => 'Indhold',
                        'name' => 'content',
                        'type' => 'flexible_content',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'button_label' => 'Tilføj indhold',
                        'min' => '',
                        'max' => '',
                        'layouts' => array(
                            array(
                                'key' => '5641cf796a554',
                                'name' => 'layout-hero',
                                'label' => 'Hero',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_564205f1e95ef',
                                        'label' => 'Tekst',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_564205bee95ee',
                                        'label' => 'Wysiwyg',
                                        'name' => 'content-wysiwyg',
                                        'type' => 'wysiwyg',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ),
                                    array(
                                        'key' => 'field_56420628e95f1',
                                        'label' => 'Medier',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'top',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_56420634e95f2',
                                        'label' => 'Billede',
                                        'name' => 'content-image',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'preview_size' => 'medium',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array(
                                        'key' => 'field_56420a349191c',
                                        'label' => 'Indstillinger',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_56420a3f9191d',
                                        'label' => 'Justering',
                                        'name' => 'setting-alignment',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'center' => 'Center',
                                        ),
                                        'default_value' => 'normal',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                    array(
                                        'key' => 'field_56420d3536b07',
                                        'label' => 'Højde',
                                        'name' => 'setting-height',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'full' => 'Full højde',
                                            'semi' => 'Semi full højde',
                                        ),
                                        'default_value' => 'normal',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                    array(
                                        'key' => 'field_5642f744f6c3a',
                                        'label' => 'Farve',
                                        'name' => 'setting-color',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'white' => 'Hvid',
                                            'grey' => 'Grå',
                                            'primary' => 'Primær',
                                            'secondary' => 'Sekundær',
                                        ),
                                        'default_value' => 'normal',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                    array(
                                        'key' => 'field_589f43ab88920',
                                        'label' => 'Countdown',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_589f4798aee4a',
                                        'label' => 'Aktiver countdown',
                                        'name' => 'countdown_activated',
                                        'type' => 'checkbox',
                                        'instructions' => 'Aktiver countdown for denne side',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            1 => 'Ja',
                                        ),
                                        'other_choice' => 0,
                                        'save_other_choice' => 0,
                                        'default_value' => array(
                                            'no' => 'no',
                                        ),
                                        'layout' => 'vertical',
                                        'toggle' => 0,
                                        'allow_custom' => 0,
                                        'save_custom' => 0,
                                        'return_format' => 'value',
                                    ),
                                    array(
                                        'key' => 'field_589f46ebb9e8f',
                                        'label' => 'Dato',
                                        'name' => 'countdown_date',
                                        'type' => 'date_picker',
                                        'instructions' => 'Dato der skal tælles ned til.',
                                        'required' => 1,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => 'field_589f4798aee4a',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'display_format' => 'm/d/Y',
                                        'return_format' => 'm/d/Y',
                                        'first_day' => 1,
                                    ),
                                    array(
                                        'key' => 'field_589f4469b628a',
                                        'label' => 'Time',
                                        'name' => 'countdown_hour',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => 'field_589f4798aee4a',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            '00' => '00',
                                            '01' => '01',
                                            '02' => '02',
                                            '03' => '03',
                                            '04' => '04',
                                            '05' => '05',
                                            '06' => '06',
                                            '07' => '07',
                                            '08' => '08',
                                            '09' => '09',
                                            10 => 10,
                                            11 => 11,
                                            12 => 12,
                                            13 => 13,
                                            14 => 14,
                                            15 => 15,
                                            16 => 16,
                                            17 => 17,
                                            18 => 18,
                                            19 => 19,
                                            20 => 20,
                                            21 => 21,
                                            22 => 22,
                                            23 => 23,
                                        ),
                                        'default_value' => 'no',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                    array(
                                        'key' => 'field_589f46cce5cd1',
                                        'label' => 'Minut',
                                        'name' => 'countdown_minute',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => 'field_589f4798aee4a',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            '00' => '00',
                                            '01' => '01',
                                            '02' => '02',
                                            '03' => '03',
                                            '04' => '04',
                                            '05' => '05',
                                            '06' => '06',
                                            '07' => '07',
                                            '08' => '08',
                                            '09' => '09',
                                            10 => 10,
                                            11 => 11,
                                            12 => 12,
                                            13 => 13,
                                            14 => 14,
                                            15 => 15,
                                            16 => 16,
                                            17 => 17,
                                            18 => 18,
                                            19 => 19,
                                            20 => 20,
                                            21 => 21,
                                            22 => 22,
                                            23 => 23,
                                            24 => 24,
                                            25 => 25,
                                            26 => 26,
                                            27 => 27,
                                            28 => 28,
                                            29 => 29,
                                            30 => 30,
                                            31 => 31,
                                            32 => 32,
                                            33 => 33,
                                            34 => 34,
                                            35 => 35,
                                            36 => 36,
                                            37 => 37,
                                            38 => 38,
                                            39 => 39,
                                            40 => 40,
                                            41 => 41,
                                            42 => 42,
                                            43 => 43,
                                            44 => 44,
                                            45 => 45,
                                            46 => 46,
                                            47 => 47,
                                            48 => 48,
                                            49 => 49,
                                            50 => 50,
                                            51 => 51,
                                            52 => 52,
                                            53 => 53,
                                            54 => 54,
                                            55 => 55,
                                            56 => 56,
                                            57 => 57,
                                            58 => 58,
                                            59 => 59,
                                        ),
                                        'default_value' => 'no',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array(
                                'key' => '564212c6dfc7e',
                                'name' => 'layout-text',
                                'label' => 'Tekst',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_564212c6dfc7f',
                                        'label' => 'Indhold',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_564212d2dfc86',
                                        'label' => 'Kolonner',
                                        'name' => 'content-column',
                                        'type' => 'flexible_content',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'button_label' => 'Tilføj kolonne',
                                        'min' => '',
                                        'max' => '',
                                        'layouts' => array(
                                            array(
                                                'key' => '564212e13d8cc',
                                                'name' => 'content-layout-wysiwyg',
                                                'label' => 'Wysiwyg',
                                                'display' => 'block',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_564213c54fa2b',
                                                        'label' => 'Størrelse',
                                                        'name' => 'setting-column-size',
                                                        'type' => 'radio',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => 50,
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            'full' => 1,
                                                            'half' => '1/2',
                                                            'third' => '1/3',
                                                            'quarter' => '1/4',
                                                        ),
                                                        'other_choice' => 0,
                                                        'save_other_choice' => 0,
                                                        'default_value' => 'full',
                                                        'layout' => 'horizontal',
                                                        'allow_null' => 0,
                                                        'return_format' => 'value',
                                                    ),
                                                    array(
                                                        'key' => 'field_564305415ae84',
                                                        'label' => 'Justering',
                                                        'name' => 'setting-column-align',
                                                        'type' => 'select',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => 50,
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            'normal' => 'Normal',
                                                            'center' => 'Center',
                                                        ),
                                                        'default_value' => 'normal',
                                                        'allow_null' => 0,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                        'disabled' => 0,
                                                        'readonly' => 0,
                                                        'return_format' => 'value',
                                                    ),
                                                    array(
                                                        'key' => 'field_564212fbdfc87',
                                                        'label' => 'Wysiwyg',
                                                        'name' => 'content-wysiwyg',
                                                        'type' => 'wysiwyg',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'tabs' => 'all',
                                                        'toolbar' => 'full',
                                                        'media_upload' => 1,
                                                        'delay' => 0,
                                                    ),
                                                ),
                                                'min' => '',
                                                'max' => '',
                                            ),
                                            array(
                                                'key' => '56421319dfc89',
                                                'name' => 'content-layout-image',
                                                'label' => 'Billede',
                                                'display' => 'block',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_5642e3625e9ac',
                                                        'label' => 'Størrelse',
                                                        'name' => 'setting-column-size',
                                                        'type' => 'radio',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => 50,
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            'full' => 1,
                                                            'half' => '1/2',
                                                            'third' => '1/3',
                                                            'quarter' => '1/4',
                                                        ),
                                                        'other_choice' => 0,
                                                        'save_other_choice' => 0,
                                                        'default_value' => 'full',
                                                        'layout' => 'horizontal',
                                                        'allow_null' => 0,
                                                        'return_format' => 'value',
                                                    ),
                                                    array(
                                                        'key' => 'field_5643088828a6d',
                                                        'label' => 'Justering',
                                                        'name' => 'setting-column-align',
                                                        'type' => 'select',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => 50,
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            'normal' => 'Normal',
                                                            'center' => 'Center',
                                                        ),
                                                        'default_value' => 'normal',
                                                        'allow_null' => 0,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                        'disabled' => 0,
                                                        'readonly' => 0,
                                                        'return_format' => 'value',
                                                    ),
                                                    array(
                                                        'key' => 'field_56421325dfc8a',
                                                        'label' => 'Billede',
                                                        'name' => 'content-image',
                                                        'type' => 'image',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'return_format' => 'array',
                                                        'preview_size' => 'medium',
                                                        'library' => 'all',
                                                        'min_width' => '',
                                                        'min_height' => '',
                                                        'min_size' => '',
                                                        'max_width' => '',
                                                        'max_height' => '',
                                                        'max_size' => '',
                                                        'mime_types' => '',
                                                    ),
                                                ),
                                                'min' => '',
                                                'max' => '',
                                            ),
                                            array(
                                                'key' => '5642e5a167819',
                                                'name' => 'content-layout-clearfix',
                                                'label' => 'Ny linje',
                                                'display' => 'block',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_5642f16a206b8',
                                                        'label' => 'Afstand',
                                                        'name' => 'setting-column-space',
                                                        'type' => 'select',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            'none' => 'Ingen',
                                                            'small' => 'Lille',
                                                            'large' => 'Stor',
                                                        ),
                                                        'default_value' => 'none',
                                                        'allow_null' => 0,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                        'disabled' => 0,
                                                        'readonly' => 0,
                                                        'return_format' => 'value',
                                                    ),
                                                ),
                                                'min' => '',
                                                'max' => '',
                                            ),
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_564212c6dfc83',
                                        'label' => 'Indstillinger',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_564212c6dfc84',
                                        'label' => 'Justering',
                                        'name' => 'setting-alignment',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'center' => 'Center',
                                        ),
                                        'default_value' => 'normal',
                                        'multiple' => 0,
                                        'allow_null' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                    array(
                                        'key' => 'field_56421340dfc8b',
                                        'label' => 'Bredde',
                                        'name' => 'setting-width',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'medium' => 'Mellem',
                                            'small' => 'Lille',
                                        ),
                                        'default_value' => 'normal',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                    array(
                                        'key' => 'field_5642e7fbb14c7',
                                        'label' => 'Højde',
                                        'name' => 'setting-height',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'full' => 'Full højde',
                                            'semi' => 'Semi full højde',
                                        ),
                                        'default_value' => 'normal',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                    array(
                                        'key' => 'field_5642f845f6c3b',
                                        'label' => 'Farve',
                                        'name' => 'setting-color',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'white' => 'Hvid',
                                            'grey' => 'Grå',
                                            'primary' => 'Primær',
                                            'secondary' => 'Sekundær',
                                        ),
                                        'default_value' => 'normal',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                    array(
                                        'key' => 'field_56448b3091a21',
                                        'label' => 'Padding',
                                        'name' => 'setting-padding',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'notop' => 'Ingen top',
                                            'nobottom' => 'Ingen bund',
                                            'notopbottom' => 'Ingen top og bund',
                                        ),
                                        'default_value' => 'normal',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array(
                                'key' => '56448e5938d74',
                                'name' => 'layout-jury',
                                'label' => 'Jury',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_56448e5938d75',
                                        'label' => 'Indhold',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_56448e6f38d84',
                                        'label' => 'Visning',
                                        'name' => 'setting-layout',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'jury-leader' => 'Jurygruppeledere',
                                            'jury-leader-members' => 'Jurygruppeledere & jury',
                                            'advisory-board' => 'Advisory Board',
                                        ),
                                        'default_value' => false,
                                        'multiple' => 0,
                                        'allow_null' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                    array(
                                        'key' => 'field_56448e5938d7e',
                                        'label' => 'Indstillinger',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_56448e5938d82',
                                        'label' => 'Farve',
                                        'name' => 'setting-color',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'white' => 'Hvid',
                                            'grey' => 'Grå',
                                            'primary' => 'Primær',
                                            'secondary' => 'Sekundær',
                                        ),
                                        'default_value' => 'normal',
                                        'multiple' => 0,
                                        'allow_null' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array(
                                'key' => '5643174cd16c2',
                                'name' => 'layout-sponsors',
                                'label' => 'Sponsors',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5645d4de597e8',
                                        'label' => 'Indhold',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_568bce1133de4',
                                        'label' => 'Visning',
                                        'name' => 'setting-layout',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'default' => 'Almindelig',
                                            'details' => 'Detaljeret',
                                        ),
                                        'default_value' => 'default',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                    array(
                                        'key' => 'field_5643175ed16c3',
                                        'label' => 'Sponsors',
                                        'name' => '',
                                        'type' => 'message',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Dette tilføjer alle sponserne (rækkefølgen kan ændres inde under Sponsors -> Re-Order)',
                                        'new_lines' => 'wpautop',
                                        'esc_html' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5645d4ea597e9',
                                        'label' => 'Indstillinger',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5645d4f4597ea',
                                        'label' => 'Farve',
                                        'name' => 'setting-color',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'white' => 'Hvid',
                                            'grey' => 'Grå',
                                            'primary' => 'Primær',
                                            'secondary' => 'Sekundær',
                                        ),
                                        'default_value' => 'norma',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array(
                                'key' => '5649d99eb2c14',
                                'name' => 'layout-timeline',
                                'label' => 'Timeline',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5649d99eb2c15',
                                        'label' => 'Indhold',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5649d99eb2c16',
                                        'label' => 'Timeline',
                                        'name' => 'content-timeline',
                                        'type' => 'repeater',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'collapsed' => '',
                                        'min' => 0,
                                        'max' => 0,
                                        'layout' => 'table',
                                        'button_label' => 'Add Row',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_5649dbfedd6d4',
                                                'label' => 'Milepæl',
                                                'name' => 'content-timeline-milestone',
                                                'type' => 'textarea',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'maxlength' => '',
                                                'rows' => 1,
                                                'new_lines' => 'br',
                                                'readonly' => 0,
                                                'disabled' => 0,
                                            ),
                                            array(
                                                'key' => 'field_5649dc23dd6d5',
                                                'label' => 'Titel',
                                                'name' => 'content-timeline-title',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => '',
                                                'readonly' => 0,
                                                'disabled' => 0,
                                            ),
                                            array(
                                                'key' => 'field_5649dc2fdd6d6',
                                                'label' => 'Beskrivelse',
                                                'name' => 'content-timeline-description',
                                                'type' => 'textarea',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'maxlength' => '',
                                                'rows' => '',
                                                'new_lines' => 'wpautop',
                                                'readonly' => 0,
                                                'disabled' => 0,
                                            ),
                                            array(
                                                'key' => 'field_5649dc3ddd6d7',
                                                'label' => 'Ikon',
                                                'name' => 'content-timeline-icon',
                                                'type' => 'image',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'return_format' => 'array',
                                                'preview_size' => 'thumbnail',
                                                'library' => 'all',
                                                'min_width' => '',
                                                'min_height' => '',
                                                'min_size' => '',
                                                'max_width' => '',
                                                'max_height' => '',
                                                'max_size' => '',
                                                'mime_types' => '',
                                            ),
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_5649d99eb2c17',
                                        'label' => 'Indstillinger',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5649d99eb2c18',
                                        'label' => 'Farve',
                                        'name' => 'setting-color',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => 50,
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'white' => 'Hvid',
                                            'grey' => 'Grå',
                                            'primary' => 'Primær',
                                            'secondary' => 'Sekundær',
                                        ),
                                        'default_value' => 'norma',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array(
                                'key' => '56434140b5411',
                                'name' => 'layout-twitter',
                                'label' => 'Twitter',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5645d50f597ec',
                                        'label' => 'Indhold',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_56434148b5412',
                                        'label' => 'Twitter',
                                        'name' => '',
                                        'type' => 'message',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Tilføjer tweets. (Max 1 twitter section pr side)',
                                        'new_lines' => 'wpautop',
                                        'esc_html' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5645d51d597ed',
                                        'label' => 'Indstillinger',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5645d527597ee',
                                        'label' => 'Farve',
                                        'name' => 'setting-color',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'white' => 'Hvid',
                                            'grey' => 'Grå',
                                            'primary' => 'Primær',
                                            'secondary' => 'Sekundær',
                                        ),
                                        'default_value' => 'normal',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array(
                                'key' => '5667fb3be2cf0',
                                'name' => 'layout-billetter',
                                'label' => 'Billetter',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5667fb3be2cf1',
                                        'label' => 'Indhold',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5667fb3be2cf2',
                                        'label' => 'Billet',
                                        'name' => '',
                                        'type' => 'message',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Denne byggeklods tilføjer en "Køb billetter" sektions på siden hvorfra brugere kan købe billetter.
            
            Du kan sætte de generelle indstillinger for denne byggeklodser under "Options".',
                                        'new_lines' => 'wpautop',
                                        'esc_html' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5667fb3be2cf3',
                                        'label' => 'Indstillinger',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5667fb3be2cf4',
                                        'label' => 'Farve',
                                        'name' => 'setting-color',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'white' => 'Hvid',
                                            'grey' => 'Grå',
                                            'primary' => 'Primær',
                                            'secondary' => 'Sekundær',
                                        ),
                                        'default_value' => 'normal',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array(
                                'key' => '564afa2b02c9b',
                                'name' => 'layout-gallery',
                                'label' => 'Galleri',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_564afa2b02c9c',
                                        'label' => 'Indhold',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_564afa3302ca0',
                                        'label' => 'Billeder',
                                        'name' => 'content-gallery',
                                        'type' => 'gallery',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'min' => '',
                                        'max' => '',
                                        'preview_size' => 'thumbnail',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                        'return_format' => 'array',
                                        'insert' => 'append',
                                    ),
                                    array(
                                        'key' => 'field_564afa2b02c9e',
                                        'label' => 'Indstillinger',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'left',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_564afa2b02c9f',
                                        'label' => 'Farve',
                                        'name' => 'setting-color',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'normal' => 'Normal',
                                            'white' => 'Hvid',
                                            'grey' => 'Grå',
                                            'primary' => 'Primær',
                                            'secondary' => 'Sekundær',
                                        ),
                                        'default_value' => 'normal',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'disabled' => 0,
                                        'readonly' => 0,
                                        'return_format' => 'value',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'page',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => array(
                    0 => 'the_content',
                ),
                'active' => true,
                'description' => '',
                'modified' => 1486833262,
            ));
        endif;		
    }
}
